apiVersion: apps/v1
kind: Deployment
metadata:
  name: medplux-deployment
  namespace: default
  labels:
    app: medplux
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medplux
  template:
    metadata:
      labels:
        app: medplux
    spec:
      containers:
        - name: medplux
          image: digibosstech/jenkins-docker:latest
          ports:
            - containerPort: 80
